### ISSUE TITLE
ionic 배우기

### ISSUE THREAD

**Issue by kimalec** [kimalec/TodayWeather#1]
ionic 기본적인 사항 배우기.

**Comment by kimalec** [comment]
``` bash
$ ionic start hello-ionic
Creating Ionic app in folder /Users/aleckim/WebstormProjects/hello-ionic based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project
Adding in iOS application by default
npm http GET https://registry.npmjs.org/cordova-ios
npm http 200 https://registry.npmjs.org/cordova-ios
npm http GET https://registry.npmjs.org/cordova-ios
npm http 200 https://registry.npmjs.org/cordova-ios
Added ios platform

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd hello-ionic

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html

 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs


New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
+---------------------------------------------------------+
+ New Ionic Updates for July 2015
+
+ The View App just landed. Preview your apps on any device
+ http://view.ionic.io
+
+ Invite anyone to preview and test your app
+ ionic share EMAIL
+
+ Generate splash screens and icons with ionic resource
+ http://ionicframework.com/blog/automating-icons-and-splash-screens/
+
+---------------------------------------------------------+
```

**Comment by kimalec** [comment]
Use ionic serve to start a local development server for app dev and testing.

**Comment by kimalec** [comment]
android의 경우 아래와 같은 에러가 발생하여 android 를 새로 설치

```
onic build android
Running command: /Users/aleckim/WebstormProjects/hello-ionic/hooks/after_prepare/010_add_platform_class.js /Users/aleckim/WebstormProjects/hello-ionic
add to body class: platform-android
Running command: /Users/aleckim/WebstormProjects/hello-ionic/platforms/android/cordova/build 
[Error: Please install Android target: "android-22".

Hint: Open the SDK manager by running: /Applications/Android\ Studio.app/sdk/tools/android
You will require:
1. "SDK Platform" for android-22
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)]
ERROR building one of the platforms: Error: /Users/aleckim/WebstormProjects/hello-ionic/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/aleckim/WebstormProjects/hello-ionic/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

andorid 새로 설치시에도 에러가 발생하여 아래의 페이지를 참고하여 해결
http://stackoverflow.com/questions/30004209/the-following-sdk-components-were-not-installed-sys-img-x86-addon-google-apis
http://stackoverflow.com/questions/17625622/how-to-completely-uninstall-android-studio/18458893#18458893

**Comment by kimalec** [comment]
webstorm에서 ionic 돌리기
https://www.jetbrains.com/webstorm/help/using-phonegap-cordova.html#d241400e54

**Comment by kimalec** [comment]
갤럭시6 개발자모드 설정법

설정 -> 디바이스정보 

에서 '빌드 번호'를 7번 탭한다.

다시 빠져나오면 '개발자 옵션' 메뉴가 추가되어 있다.

**Comment by kimalec** [comment]
http://daniel.favand.net/2014/11/21/developing-ionic-cordova-apps-in-the-cloud-with-cloud9/
https://docs.c9.io/docs/ionic
